<div class="well">
	<h3>Apache Error Log</h3>

	<table class="table">
		<?php foreach ($this->_view['apacheErrorLogFiles'] as $file): ?>
			<tr>
				<td>
					<p><a href="/log/show?dir=<?= base64_encode($file->getPath()) ?>&file=apache.error"><?= $file->getName() ?></a></p>
				</td>
				<td class="text-right">
					<?= \Application\Helper\File::formatFilesize($file->getSize()) ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>

<div class="well">
	<h3>Apache Access Log</h3>

	<table class="table">
		<?php foreach ($this->_view['apacheAccessLogFiles'] as $file): ?>
			<tr>
				<td>
					<p><a href="/log/show?dir=<?= base64_encode($file->getPath()) ?>&file=apache.access"><?= $file->getName() ?></a></p>
				</td>
				<td class="text-right">
					<?= \Application\Helper\File::formatFilesize($file->getSize()) ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>