<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="author" content="Chris Herden" />

		<title>LogWuehler</title>

		<link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
		<link href="/lib/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" />
		<link href="/css/style.css" rel="stylesheet" />
		
		<script src="/lib/jquery/jquery.js"></script>
	</head>

	<body>

		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">LogWuehler</a>
				</div>
			</div>
		</div>

		<div class="container">

			<?= $this->_renderView() ?>

		</div>
		
		<script src="/lib/jquery.validate/jquery.validate.min.js"></script>
		<script src="/lib/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>
