<?php

 use Application\Helper\Language; ?>

<h2><?= Language::translate('cn.install.index.title') ?></h2>

<form role="form" action="/install/index" method="post">

	<?php
	$https = filter_input(INPUT_SERVER, 'HTTPS');
	if (empty($https)):
		?>
		<div class="alert alert-warning">
			<?= Language::translate('cn.install.index.warning.https') ?>
		</div>
	<?php endif; ?>

	<?php if (is_null($_SERVER['PHP_AUTH_USER'])): ?>
		<div class="alert alert-warning">
			<?= Language::translate('cn.install.index.warning.httpauth') ?>
		</div>
	<?php endif; ?>

	<div class="well">
		<h3><?= Language::translate('cn.install.index.requirements.title') ?></h3>

		<?= Language::translate('cn.install.index.requirements.writeable') ?>
		<?php if ($this->_view['permission']['config'] == true): ?>
			<span class="label label-success">TRUE</span>
		<?php else: ?>
			<span class="label label-danger">FALSE</span>
		<?php endif; ?>
		<br />
		<?= Language::translate('cn.install.index.requirements.phpversion') ?>
		<?php if ($this->_view['permission']['phpversion'] == true): ?>
			<span class="label label-success">TRUE</span>
		<?php else: ?>
			<span class="label label-danger">FALSE</span>
		<?php endif; ?>
	</div>

	<?php if ($this->_view['success'] === true): ?>
		<div class="alert alert-success">
			<?= Language::translate('cn.install.index.message.success') ?><br />
			<a href="/"><?= Language::translate('cn.install.index.link.con') ?></a>
		</div>
	<?php endif; ?>
	<?php if ($this->_view['error']['file'] === true): ?>
		<div class="alert alert-danger">
			<strong><?= Language::translate('cn.install.index.message.error.title') ?></strong><br />
			<?= Language::translate('cn.install.index.message.error.body') ?>
		</div>
	<?php endif; ?>

	<div class="row">
		<div class="col-md-6">
			<div class="well">
				<?php if ($this->_view['error']['apacheError'] == true): ?>
					<div class="alert alert-danger">
						<strong><?= Language::translate('cn.install.index.file.message.error.title') ?></strong><br />
						<?= Language::translate('cn.install.index.file.message.error.body') ?>
					</div>
				<?php endif; ?>

				<h3><?= Language::translate('cn.install.index.file.apache.error.title') ?></h3>

				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.apache.error.dir') ?></label>
					<input type="text" name="apacheErrorPath" value="/var/log/apache2" class="form-control" />
				</div>
				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.apache.error.keyword') ?></label>
					<input type="text" name="apacheErrorKeyword" value="error" class="form-control" />
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="well">
				<?php if ($this->_view['error']['apacheAccess'] == true): ?>
					<div class="alert alert-danger">
						<strong><?= Language::translate('cn.install.index.file.message.error.title') ?></strong><br />
						<?= Language::translate('cn.install.index.file.message.error.body.') ?>
					</div>
				<?php endif; ?>

				<h3><?= Language::translate('cn.install.index.file.apache.access.title') ?></h3>

				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.apache.access.dir') ?></label>
					<input type="text" name="apacheAccessPath" value="/var/log/apache2" class="form-control" />
				</div>
				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.apache.access.keyword') ?></label>
					<input type="text" name="apacheAccessKeyword" value="access" class="form-control" />
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<div class="well">
				<?php if ($this->_view['error']['nginxError'] == true): ?>
					<div class="alert alert-danger">
						<strong><?= Language::translate('cn.install.index.file.message.error.title') ?></strong><br />
						<?= Language::translate('cn.install.index.file.message.error.body') ?>
					</div>
				<?php endif; ?>

				<h3><?= Language::translate('cn.install.index.file.nginx.error.title') ?></h3>

				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.nginx.error.dir') ?></label>
					<input type="text" name="nginxErrorPath" value="/var/log/nginx" class="form-control" />
				</div>
				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.nginx.error.keyword') ?></label>
					<input type="text" name="nginxErrorKeyword" value="error" class="form-control" />
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="well">
				<?php if ($this->_view['error']['nginxAccess'] == true): ?>
					<div class="alert alert-danger">
						<strong><?= Language::translate('cn.install.index.file.message.error.title') ?></strong><br />
						<?= Language::translate('cn.install.index.file.message.error.body.') ?>
					</div>
				<?php endif; ?>

				<h3><?= Language::translate('cn.install.index.file.nginx.access.title') ?></h3>

				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.nginx.access.dir') ?></label>
					<input type="text" name="nginxAccessPath" value="/var/log/nginx" class="form-control" />
				</div>
				<div class="form-group">
					<label><?= Language::translate('cn.install.index.file.nginx.access.keyword') ?></label>
					<input type="text" name="nginxAccessKeyword" value="access" class="form-control" />
				</div>
			</div>
		</div>
	</div>

	<input type="submit" class="btn btn-primary btn-lg" value="<?= Language::translate('cn.install.index.btn.install') ?>" <?= (array_search(false, $this->_view['permission']) !== false) ? 'disabled="disabled"' : '' ?> />
	<br /><br />
</form>